//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentEntities1 : DbContext
    {
        public CarRentEntities1()
            : base("name=CarRentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cartable> Cartables { get; set; }
        public virtual DbSet<CustomerName> CustomerNames { get; set; }
        public virtual DbSet<NameTable> NameTables { get; set; }
        public virtual DbSet<UserNameTable> UserNameTables { get; set; }
    }
}
