//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerName
    {
        public int customer_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Car_id { get; set; }
        public string Dob { get; set; }
    }
}
